# Generated by Django 4.0 on 2022-07-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_title'),
        ('invoicecemgmt', '0002_remove_invoice_id_invoice_line_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 1'),
        ),
    ]
