# Generated by Django 4.0 on 2022-07-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_title'),
        ('invoicecemgmt', '0003_invoice_line_eight_invoice_line_eight_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory', to_field='title'),
        ),
    ]
