# Generated by Django 4.0 on 2022-07-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0007_alter_inventory_title'),
        ('invoicecemgmt', '0003_alter_invoice_line_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 8'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 9'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 7'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 6'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 10'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventory', verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='Customer/Retailer Name'),
        ),
    ]
