# Generated by Django 4.0 on 2022-07-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_title'),
        ('invoicecemgmt', '0005_alter_invoice_line_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory', to_field='title'),
        ),
    ]
