# Generated by Django 4.0 on 2022-07-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_title'),
        ('invoicecemgmt', '0007_alter_invoice_line_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_eight_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (Rs)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (Rs)'),
        ),
    ]
