# Generated by Django 4.0 on 2022-07-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_title'),
        ('invoicecemgmt', '0008_alter_invoice_line_eight_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', to_field='title'),
        ),
    ]
