# Generated by Django 4.0 on 2022-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicecemgmt', '0010_alter_invoice_line_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price(₹)'),
        ),
    ]
