# Generated by Django 4.0 on 2022-07-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_id_alter_inventory_product_number'),
        ('invoicecemgmt', '0011_alter_invoice_line_one_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 8'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 9'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 7'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 6'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 10'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventory', verbose_name='Line 2'),
        ),
    ]
