# Generated by Django 4.0 on 2022-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('ph_no', models.CharField(blank=True, default='', max_length=13, unique=True, verbose_name='Phone Number')),
            ],
        ),
    ]
