# Generated by Django 4.0.4 on 2022-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
