# Generated by Django 4.0 on 2022-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120, null=True, unique=True, verbose_name='Title'),
        ),
    ]
