# Generated by Django 4.0 on 2022-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Unit Price'),
        ),
    ]
