# Generated by Django 4.0 on 2022-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
